# Generated by Django 4.1.7 on 2023-04-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('cod_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('num_serie', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tpo_Articulos',
            fields=[
                ('id_tpo_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tpo_Operaciones',
            fields=[
                ('id_tpo_operacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('fecha_sistema', models.DateField(auto_created=True)),
                ('id_operacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.articulos')),
                ('id_tpo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.tpo_operaciones')),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.marcas'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_tpo_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.tpo_articulos'),
        ),
    ]
