# Generated by Django 4.2.1 on 2023-06-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('cod_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('total_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('num_serie', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('cod_articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tpo_Articulos',
            fields=[
                ('id_tpo_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tpo_Movimientos',
            fields=[
                ('id_tpo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fecha_sistema', models.DateField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.inventario')),
                ('id_tpo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.tpo_movimientos')),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.marcas'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_tpo_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.tpo_articulos'),
        ),
    ]
