# Generated by Django 4.1.7 on 2023-04-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_movimientos_fecha_sistema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='id_tpo_operacion',
            new_name='id_tpo_movimiento',
        ),
    ]
