# Generated by Django 4.1.7 on 2023-04-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_id_tpo_operacion_movimientos_id_tpo_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='id_articulo',
            new_name='cod_articulo',
        ),
    ]
