# Generated by Django 4.1.7 on 2023-05-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_articulos_modelo_remove_articulos_num_serie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Inventario',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='id_stock',
            new_name='id_inventario',
        ),
    ]
