# Generated by Django 4.1.7 on 2023-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_inventario_cod_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='total_stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
