# Generated by Django 4.1.7 on 2023-05-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_articulos_total_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='cod_articulo',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='id_inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.inventario'),
            preserve_default=False,
        ),
    ]
